### ISSUE TITLE
Magento 2.4.x

### ISSUE THREAD

**Issue by CrazyICT** [magently/mde#1]
To give this compatibility for Magento 2.4 you need to add sockets. 

Dockerfile:

`RUN docker-php-ext-install -j$(nproc) \
    gd \
    soap \
    bcmath \
    intl \
    pdo_mysql \
    simplexml \
    xsl \
    zip \
    **sockets**`

**Comment by magently** [comment]
Support for Magento 2.4.x has been added here: https://github.com/magently/mde/commit/1a8f6edbe71bc1bd87e85e8ef1865483e1359a62

We're sorry it took so long
